import { Case } from '../models/Case.js';
import { Evidence } from '../models/Evidence.js';
import { Hypothesis } from '../models/Hypothesis.js';
import { EvidenceRelationship } from '../models/EvidenceRelationship.js';
import { AuditLog } from '../models/AuditLog.js';
import { calculateHypothesisConfidence } from './confidenceScore.service.js';

export async function generateCaseReport(caseId) {
  const [caseDoc, evidenceList, rawHypotheses, relationships, auditLogs] = await Promise.all([
    Case.findById(caseId)
      .populate('createdBy', 'name email role')
      .populate('assignedInvestigators', 'name email role')
      .populate('assignedSupervisor', 'name email role')
      .lean(),
    Evidence.find({ caseId })
      .populate('collectedBy', 'name email')
      .populate('verifiedBy', 'name email')
      .sort({ collectedAt: 1 })
      .lean(),
    Hypothesis.find({ caseId }).lean(),
    EvidenceRelationship.find({ caseId })
      .populate('sourceEvidenceId', 'title type')
      .populate('targetEvidenceId', 'title type')
      .lean(),
    AuditLog.find({ caseId })
      .populate('actorId', 'name email role')
      .sort({ timestamp: 1 })
      .lean()
  ]);

  if (!caseDoc) {
    throw new Error('Case not found');
  }

  const hypothesesWithScores = [];
  for (const h of rawHypotheses) {
    const analysis = await calculateHypothesisConfidence(h._id);
    hypothesesWithScores.push({
      ...h,
      confidenceScore: analysis.confidenceScore,
      breakdown: analysis.breakdown,
      conflicts: analysis.conflicts
    });
  }

  const verifiedEvidenceCount = evidenceList.filter((e) => e.verificationStatus === 'verified').length;
  const rejectedEvidenceCount = evidenceList.filter((e) => e.verificationStatus === 'rejected').length;

  const reportGeneratedAt = new Date().toISOString();

  // Generate clean Markdown representation
  const markdownContent = `# Forensic Investigation Report
**Case ID:** ${caseDoc._id}
**Title:** ${caseDoc.title}
**Status:** ${caseDoc.status.toUpperCase()} | **Priority:** ${caseDoc.priority.toUpperCase()}
**Generated:** ${new Date(reportGeneratedAt).toUTCString()}
**Investigative Unit:** ${caseDoc.createdBy?.name || 'Lead Investigator'} (${caseDoc.createdBy?.email})

---

## 1. Executive Summary
${caseDoc.description}

- **Total Evidence Artifacts:** ${evidenceList.length} (${verifiedEvidenceCount} verified, ${rejectedEvidenceCount} rejected)
- **Competing Hypotheses Formulated:** ${hypothesesWithScores.length}
- **Audit Trail Entries:** ${auditLogs.length} logged state transitions

---

## 2. Forensic Evidence Register
| Item ID | Title | Type | Source | Verification | SHA-256 Hash |
|---|---|---|---|---|---|
${evidenceList.map((e) => `| ${e._id} | ${e.title} | ${e.type} | ${e.source} | ${e.verificationStatus.toUpperCase()} | \`${e.fileHash || 'N/A'}\` |`).join('\n')}

---

## 3. Competing Analytical Hypotheses & Confidence Models
${hypothesesWithScores.map((h, idx) => `
### Hypothesis ${idx + 1}: ${h.title}
- **Investigator Judgment:** ${h.status.toUpperCase()}
- **Deterministic Confidence Score:** **${h.confidenceScore}%**
- **Evidence Breakdown:**
${(h.breakdown || []).map((b) => `  - [${b.stance.toUpperCase()}] ${b.title} (${b.counted ? `Contribution: ${b.effectiveContribution > 0 ? '+' : ''}${b.effectiveContribution}` : 'Unverified: 0.00'})`).join('\n')}
${(h.conflicts || []).map((c) => `  - ⚠️ **Conflict Flag:** ${c.message}`).join('\n')}
`).join('\n')}

---

## 4. Evidence Topology & Relationship Network
${relationships.length === 0 ? '_No evidence-to-evidence relationships recorded._' : relationships.map((r) => `- **[${r.relationshipType.toUpperCase()}]** "${r.sourceEvidenceId?.title}" → "${r.targetEvidenceId?.title}" (Weight: ${r.weight})${r.notes ? ` — *Note:* ${r.notes}` : ''}`).join('\n')}

---

## 5. Immutable Chain of Custody & Audit Timeline
${auditLogs.map((a) => `- \`[${new Date(a.timestamp).toISOString()}]\` **${a.action}** by **${a.actorId?.name || 'System'}** (${a.actorId?.email || 'N/A'})${a.metadata ? ` - ${JSON.stringify(a.metadata)}` : ''}`).join('\n')}

---
*Report generated by BlackBox Digital Evidence Platform. All cryptographic hashes and audit records verified.*
`;

  return {
    reportId: `REP-${caseDoc._id}-${Date.now()}`,
    caseId: caseDoc._id,
    case: caseDoc,
    evidenceSummary: {
      total: evidenceList.length,
      verified: verifiedEvidenceCount,
      rejected: rejectedEvidenceCount,
      unverified: evidenceList.length - verifiedEvidenceCount - rejectedEvidenceCount,
      items: evidenceList
    },
    hypotheses: hypothesesWithScores,
    relationships,
    auditLogs,
    generatedAt: reportGeneratedAt,
    markdown: markdownContent
  };
}
